version: "3.7"
services:
    app:
        build:
            args:
                user: 1000
                uid: 1000
            context: ./
            dockerfile: Dockerfile.dev
        environment:
            VITE_PORT: ${VITE_SERVER_PORT}
            PHP_IDE_CONFIG: serverName=hexletBlog
        image: hexlet-blog
        container_name: hexlet-blog-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - hexlet_blog
        ports:
            - ${VITE_SERVER_PORT}:${VITE_SERVER_PORT} # both from .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
    db:
        image: postgres:16-alpine
        container_name: hexlet-blog-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: hexlet_blog
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
        ports:
            - "33022:5432"
        volumes:
            - ./docker-compose/postgres:/var/lib/postgresql/data
        networks:
            - hexlet_blog
    nginx:
        image: nginx:1.25-alpine
        container_name: hexlet-blog-nginx
        restart: unless-stopped
        ports:
            - 8022:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - hexlet_blog

networks:
    hexlet_blog:
        driver: bridge
